services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-qr-app
    restart: unless-stopped
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_qr
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-qr-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel-qr-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-qr-network

networks:
  laravel-qr-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
